In [2]:
from google.cloud import bigquery
#import pandas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import entropy
from google.cloud import bigquery

client = bigquery.Client(location="US", project="lcg-bi-mia-dev")  #SELECT THE PROJECT
#print("Client creating using default project: {}".format(client.project))

In [3]:
##ALL Active Accounts:

query_all = """
select PLAYER_ID ,
Classification_Date ,
ACTIVE_DAY_QTY ,
M20_SPENDFROMNORM ,
M02_TIMEONSITE ,
MARKER_3_FREQ_PLAY_INCREASE ,
M04_DEPOSITDAYS ,
M05_FAILEDDEPOSITS ,
M06_MULTIPLEPAYMENTMETHODS ,
M07_LATENIGHTPLAY ,
M19_TIMEONSITEL7D ,
M01_DEPOSITAMOUNTINCREASE ,
M03_INCREASINGSTAKES ,
MO8_TIMEBETWEENSESSIONS ,
MO9_DUPLICATEACCOUNTS ,
M10_SPEEDOFPLAY ,
M11_INSESSIONTOPUP ,
M12_RGLIMITEXCEEDED ,
M13_CHAOTICPLAY ,
M14_VARIETYOFGAMES ,
M15_YESTERDAYTIMEONSITE ,
M16_PLAYINWORKHOURS ,
M17_BIGWINNODEPOSIT ,
M18_DEPOSIT_QTY ,
M21_INCREASINGSTAKESRATIO ,
TENURE_DAYS ,
DAYS_SINCE_REGISTRATION ,
PLAYER_DAYS_L28D ,
TURNOVER_L28D ,
NGR_L28D ,
DEPOSIT_L28D ,
WITHDRAWAL_L28D ,
M03_INCREASINGSTAKES_BINGO ,
M03_INCREASINGSTAKE_SPORTS_INPLAY ,
M03_INCREASINGSTAKES_PREMATCH ,
M03_INCREASINGSTAKE_SLOTS ,
M03_INCREASINGSTAKES_OTHER_CASINO ,
M03_INCREASINGSTAKEs_VIRTUAL ,
M03_INCREASINGSTAKES_TABLE_GAMES ,
M03_INCREASINGSTAKES_OTHER ,
M02_TIMEONSITE_BINGO ,
M02_TIMEONSITE_SPORTS ,
M02_TIMEONSITE_CASINO ,
M02_TIMEONSITE_POKER ,
M07_LATENIGHTPLAY_BINGO ,
M07_LATENIGHTPLAY_SPORTS ,
M07_LATENIGHTPLAY_CASINO ,
M07_LATENIGHTPLAY_POKER ,
M13_CHAOTICPLAY_BINGO ,
M13_CHAOTICPLAY_SPORTS_INPLAY ,
M13_CHAOTICPLAY_SPORTS_PREMATCH ,
M13_CHAOTICPLAY_SLOTS ,
M13_CHAOTICPLAY_OTHER_CASINO ,
M13_CHAOTICPLAY_VIRTUAL ,
M13_CHAOTICPLAY_TABLE_GAMES ,
M13_CHAOTICPLAY_OTHER ,
M15_YESTERDAYTIMEONSITE_BINGO ,
M15_YESTERDAYTIMEONSITE_SPORTS ,
M15_YESTERDAYTIMEONSITE_CASINO ,
M15_YESTERDAYTIMEONSITE_POKER ,
M19_TIMEONSITEL7D_BINGO ,
M19_TIMEONSITEL7D_SPORTS ,
M19_TIMEONSITEL7D_CASINO ,
M19_TIMEONSITEL7D_POKER ,
M25_TURNOVER_L28D_BINGO ,
M25_TURNOVER_L28D_SPORTS_PREMATCH ,
M25_TURNOVER_L28D_SPORTS_INPLAY ,
M25_TURNOVER_L28D_BINGO_SLOTS ,
M25_TURNOVER_L28D_BINGO_OTHER_CASINO ,
M25_TURNOVER_L28D_BINGO_VIRTUAL ,
M25_TURNOVER_L28D_BINGO_TABLE_GAMES ,
M25_TURNOVER_L28D_BINGO_OTHER  
from 

(

select 

row_number() OVER (PARTITION BY PLAYER_ID ORDER BY RAND) row_num, a.*

from

(
SELECT 
(cast(rand()*1000 as int)) as RAND,
a.PLAYER_ID,
a.Classification_Date,
a.ACTIVE_DAY_QTY,
a.M20_SPENDFROMNORM,
a.M02_TIMEONSITE,
a.MARKER_3_FREQ_PLAY_INCREASE,
a.M04_DEPOSITDAYS,
a.M05_FAILEDDEPOSITS,
a.M06_MULTIPLEPAYMENTMETHODS,
a.M07_LATENIGHTPLAY,
a.M19_TIMEONSITEL7D,
a.M01_DEPOSITAMOUNTINCREASE,
a.M03_INCREASINGSTAKES,
a.MO8_TIMEBETWEENSESSIONS,
a.MO9_DUPLICATEACCOUNTS,
a.M10_SPEEDOFPLAY,
a.M11_INSESSIONTOPUP,
a.M12_RGLIMITEXCEEDED,
a.M13_CHAOTICPLAY,
a.M14_VARIETYOFGAMES,
a.M15_YESTERDAYTIMEONSITE,
a.M16_PLAYINWORKHOURS,
a.M17_BIGWINNODEPOSIT,
a.M18_DEPOSIT_QTY,
a.M21_INCREASINGSTAKESRATIO,
a.TENURE_DAYS,
a.DAYS_SINCE_REGISTRATION,
a.PLAYER_DAYS_L28D,
a.TURNOVER_L28D,
a.NGR_L28D,
a.DEPOSIT_L28D,
a.WITHDRAWAL_L28D,

c.M03_INCREASINGSTAKES_BINGO,
c.M03_INCREASINGSTAKE_SPORTS_INPLAY,
c.M03_INCREASINGSTAKES_PREMATCH,
c.M03_INCREASINGSTAKE_SLOTS,
c.M03_INCREASINGSTAKES_OTHER_CASINO,
c.M03_INCREASINGSTAKEs_VIRTUAL,
c.M03_INCREASINGSTAKES_TABLE_GAMES,
c.M03_INCREASINGSTAKES_OTHER,
c.M02_TIMEONSITE_BINGO,
c.M02_TIMEONSITE_SPORTS,
c.M02_TIMEONSITE_CASINO,
c.M02_TIMEONSITE_POKER,
c.M07_LATENIGHTPLAY_BINGO,
c.M07_LATENIGHTPLAY_SPORTS,
c.M07_LATENIGHTPLAY_CASINO,
c.M07_LATENIGHTPLAY_POKER,
c.M13_CHAOTICPLAY_BINGO,
c.M13_CHAOTICPLAY_SPORTS_INPLAY,
c.M13_CHAOTICPLAY_SPORTS_PREMATCH,
c.M13_CHAOTICPLAY_SLOTS,
c.M13_CHAOTICPLAY_OTHER_CASINO,
c.M13_CHAOTICPLAY_VIRTUAL,
c.M13_CHAOTICPLAY_TABLE_GAMES,
c.M13_CHAOTICPLAY_OTHER,
c.M15_YESTERDAYTIMEONSITE_BINGO,
c.M15_YESTERDAYTIMEONSITE_SPORTS,
c.M15_YESTERDAYTIMEONSITE_CASINO,
c.M15_YESTERDAYTIMEONSITE_POKER,
c.M19_TIMEONSITEL7D_BINGO,
c.M19_TIMEONSITEL7D_SPORTS,
c.M19_TIMEONSITEL7D_CASINO,
c.M19_TIMEONSITEL7D_POKER,
c.M25_TURNOVER_L28D_BINGO,
c.M25_TURNOVER_L28D_SPORTS_PREMATCH,
c.M25_TURNOVER_L28D_SPORTS_INPLAY,
c.M25_TURNOVER_L28D_BINGO_SLOTS,
c.M25_TURNOVER_L28D_BINGO_OTHER_CASINO,
c.M25_TURNOVER_L28D_BINGO_VIRTUAL,
c.M25_TURNOVER_L28D_BINGO_TABLE_GAMES,
c.M25_TURNOVER_L28D_BINGO_OTHER,


 
 FROM `lcg-bi-mia-dev.SANDPITADA.PLAYER_MOP_MARKERS` a

join `lcg-bi-mia-dev.SANDPITADA.PLAYER_MOP_MARKERS_V3` c on a.PLAYER_ID = c.player_id and a.Classification_Date = c.Classification_Date
 where extract(year from a.Classification_Date) in (2020,2021) 
 and a.PLAYER_ID not in (select player_id from `lcg-bi-mia-dev.SANDPITADA.PG_Target_v3_playerid`)
#group by  extract(year from a.Classification_Date)
and right(cast(a.PLAYER_ID as string),1) in ('3')
 order by a.PLAYER_ID
)a
 
)b where b.row_num = 1
        
"""
query_job = client.query(
    query_all,
    # Location must match that of the dataset(s) referenced in the query.
    location="EU",
)  # API request - starts the query

df_all = query_job.to_dataframe()
df_all.head()

,PLAYER_ID,Classification_Date,ACTIVE_DAY_QTY,M20_SPENDFROMNORM,M02_TIMEONSITE,MARKER_3_FREQ_PLAY_INCREASE,M04_DEPOSITDAYS,M05_FAILEDDEPOSITS,M06_MULTIPLEPAYMENTMETHODS,M07_LATENIGHTPLAY,...,M19_TIMEONSITEL7D_CASINO,M19_TIMEONSITEL7D_POKER,M25_TURNOVER_L28D_BINGO,M25_TURNOVER_L28D_SPORTS_PREMATCH,M25_TURNOVER_L28D_SPORTS_INPLAY,M25_TURNOVER_L28D_BINGO_SLOTS,M25_TURNOVER_L28D_BINGO_OTHER_CASINO,M25_TURNOVER_L28D_BINGO_VIRTUAL,M25_TURNOVER_L28D_BINGO_TABLE_GAMES,M25_TURNOVER_L28D_BINGO_OTHER
0,21299973,2021-06-09,1649,0E-9,0.077920000,0.077920000,NaN,NaN,NaN,None,...,0.016670000,0E-9,0E-9,0E-9,0E-9,3.530250000,0E-9,0E-9,0E-9,0E-9
1,184787803,2021-06-12,312,-5.186150000,1.736180000,1.736180000,6.0,2.0,1.0,0.900000000,...,2.600000000,0E-9,0E-9,0E-9,0E-9,2948.132300000,586.517470000,0E-9,87.583310000,3493.750280000
2,190191163,2020-11-18,43,None,0.648630000,0.648630000,NaN,NaN,NaN,None,...,0E-9,0E-9,0E-9,1.370000000,0E-9,0E-9,0E-9,0E-9,0E-9,19.840420000
3,190841223,2021-06-14,81,1.230770000,2.222220000,2.222220000,2.0,NaN,1.0,None,...,0.083330000,0E-9,0E-9,0E-9,0E-9,40.789630000,0E-9,0E-9,0E-9,0E-9
4,199207053,2020-12-30,32,None,9.372280000,9.372280000,2.0,NaN,1.0,None,...,7.150000000,0E-9,0E-9,0E-9,0E-9,1443.163130000,28.410000000,0E-9,0E-9,0E-9

In [4]:
df_all['M20_SPENDFROMNORM'] = df_all['M20_SPENDFROMNORM'].astype(object).astype(float) 
df_all['M02_TIMEONSITE'] = df_all['M02_TIMEONSITE'].astype(object).astype(float) 
df_all['MARKER_3_FREQ_PLAY_INCREASE'] = df_all['MARKER_3_FREQ_PLAY_INCREASE'].astype(object).astype(float) 
df_all['M07_LATENIGHTPLAY'] = df_all['M07_LATENIGHTPLAY'].astype(object).astype(float) 
df_all['M19_TIMEONSITEL7D'] = df_all['M19_TIMEONSITEL7D'].astype(object).astype(float) 
df_all['M01_DEPOSITAMOUNTINCREASE'] = df_all['M01_DEPOSITAMOUNTINCREASE'].astype(object).astype(float) 
df_all['M03_INCREASINGSTAKES'] = df_all['M03_INCREASINGSTAKES'].astype(object).astype(float) 
df_all['MO8_TIMEBETWEENSESSIONS'] = df_all['MO8_TIMEBETWEENSESSIONS'].astype(object).astype(float) 
df_all['M10_SPEEDOFPLAY'] = df_all['M10_SPEEDOFPLAY'].astype(object).astype(float) 
df_all['M11_INSESSIONTOPUP'] = df_all['M11_INSESSIONTOPUP'].astype(object).astype(float) 
df_all['M13_CHAOTICPLAY'] = df_all['M13_CHAOTICPLAY'].astype(object).astype(float) 
df_all['M15_YESTERDAYTIMEONSITE'] = df_all['M15_YESTERDAYTIMEONSITE'].astype(object).astype(float) 
df_all['M16_PLAYINWORKHOURS'] = df_all['M16_PLAYINWORKHOURS'].astype(object).astype(float) 
df_all['M21_INCREASINGSTAKESRATIO'] = df_all['M21_INCREASINGSTAKESRATIO'].astype(object).astype(float) 
df_all['TURNOVER_L28D'] = df_all['TURNOVER_L28D'].astype(object).astype(float) 
df_all['NGR_L28D'] = df_all['NGR_L28D'].astype(object).astype(float) 
df_all['DEPOSIT_L28D'] = df_all['DEPOSIT_L28D'].astype(object).astype(float) 
df_all['WITHDRAWAL_L28D'] = df_all['WITHDRAWAL_L28D'].astype(object).astype(float) 
df_all['M03_INCREASINGSTAKES_BINGO'] = df_all['M03_INCREASINGSTAKES_BINGO'].astype(object).astype(float) 
df_all['M03_INCREASINGSTAKE_SPORTS_INPLAY'] = df_all['M03_INCREASINGSTAKE_SPORTS_INPLAY'].astype(object).astype(float) 
df_all['M03_INCREASINGSTAKES_PREMATCH'] = df_all['M03_INCREASINGSTAKES_PREMATCH'].astype(object).astype(float) 
df_all['M03_INCREASINGSTAKE_SLOTS'] = df_all['M03_INCREASINGSTAKE_SLOTS'].astype(object).astype(float) 
df_all['M03_INCREASINGSTAKES_OTHER_CASINO'] = df_all['M03_INCREASINGSTAKES_OTHER_CASINO'].astype(object).astype(float) 
df_all['M03_INCREASINGSTAKEs_VIRTUAL'] = df_all['M03_INCREASINGSTAKEs_VIRTUAL'].astype(object).astype(float) 
df_all['M03_INCREASINGSTAKES_TABLE_GAMES'] = df_all['M03_INCREASINGSTAKES_TABLE_GAMES'].astype(object).astype(float) 
df_all['M03_INCREASINGSTAKES_OTHER'] = df_all['M03_INCREASINGSTAKES_OTHER'].astype(object).astype(float) 
df_all['M02_TIMEONSITE_BINGO'] = df_all['M02_TIMEONSITE_BINGO'].astype(object).astype(float) 
df_all['M02_TIMEONSITE_SPORTS'] = df_all['M02_TIMEONSITE_SPORTS'].astype(object).astype(float) 
df_all['M02_TIMEONSITE_CASINO'] = df_all['M02_TIMEONSITE_CASINO'].astype(object).astype(float) 
df_all['M02_TIMEONSITE_POKER'] = df_all['M02_TIMEONSITE_POKER'].astype(object).astype(float) 
df_all['M07_LATENIGHTPLAY_BINGO'] = df_all['M07_LATENIGHTPLAY_BINGO'].astype(object).astype(float) 
df_all['M07_LATENIGHTPLAY_SPORTS'] = df_all['M07_LATENIGHTPLAY_SPORTS'].astype(object).astype(float) 
df_all['M07_LATENIGHTPLAY_CASINO'] = df_all['M07_LATENIGHTPLAY_CASINO'].astype(object).astype(float) 
df_all['M07_LATENIGHTPLAY_POKER'] = df_all['M07_LATENIGHTPLAY_POKER'].astype(object).astype(float) 
df_all['M13_CHAOTICPLAY_BINGO'] = df_all['M13_CHAOTICPLAY_BINGO'].astype(object).astype(float) 
df_all['M13_CHAOTICPLAY_SPORTS_INPLAY'] = df_all['M13_CHAOTICPLAY_SPORTS_INPLAY'].astype(object).astype(float) 
df_all['M13_CHAOTICPLAY_SPORTS_PREMATCH'] = df_all['M13_CHAOTICPLAY_SPORTS_PREMATCH'].astype(object).astype(float) 
df_all['M13_CHAOTICPLAY_SLOTS'] = df_all['M13_CHAOTICPLAY_SLOTS'].astype(object).astype(float) 
df_all['M13_CHAOTICPLAY_OTHER_CASINO'] = df_all['M13_CHAOTICPLAY_OTHER_CASINO'].astype(object).astype(float) 
df_all['M13_CHAOTICPLAY_VIRTUAL'] = df_all['M13_CHAOTICPLAY_VIRTUAL'].astype(object).astype(float) 
df_all['M13_CHAOTICPLAY_TABLE_GAMES'] = df_all['M13_CHAOTICPLAY_TABLE_GAMES'].astype(object).astype(float) 
df_all['M13_CHAOTICPLAY_OTHER'] = df_all['M13_CHAOTICPLAY_OTHER'].astype(object).astype(float) 
df_all['M15_YESTERDAYTIMEONSITE_BINGO'] = df_all['M15_YESTERDAYTIMEONSITE_BINGO'].astype(object).astype(float) 
df_all['M15_YESTERDAYTIMEONSITE_SPORTS'] = df_all['M15_YESTERDAYTIMEONSITE_SPORTS'].astype(object).astype(float) 
df_all['M15_YESTERDAYTIMEONSITE_CASINO'] = df_all['M15_YESTERDAYTIMEONSITE_CASINO'].astype(object).astype(float) 
df_all['M15_YESTERDAYTIMEONSITE_POKER'] = df_all['M15_YESTERDAYTIMEONSITE_POKER'].astype(object).astype(float) 
df_all['M19_TIMEONSITEL7D_BINGO'] = df_all['M19_TIMEONSITEL7D_BINGO'].astype(object).astype(float) 
df_all['M19_TIMEONSITEL7D_SPORTS'] = df_all['M19_TIMEONSITEL7D_SPORTS'].astype(object).astype(float) 
df_all['M19_TIMEONSITEL7D_CASINO'] = df_all['M19_TIMEONSITEL7D_CASINO'].astype(object).astype(float) 
df_all['M19_TIMEONSITEL7D_POKER'] = df_all['M19_TIMEONSITEL7D_POKER'].astype(object).astype(float) 
df_all['M25_TURNOVER_L28D_BINGO'] = df_all['M25_TURNOVER_L28D_BINGO'].astype(object).astype(float) 
df_all['M25_TURNOVER_L28D_SPORTS_PREMATCH'] = df_all['M25_TURNOVER_L28D_SPORTS_PREMATCH'].astype(object).astype(float) 
df_all['M25_TURNOVER_L28D_SPORTS_INPLAY'] = df_all['M25_TURNOVER_L28D_SPORTS_INPLAY'].astype(object).astype(float) 
df_all['M25_TURNOVER_L28D_BINGO_SLOTS'] = df_all['M25_TURNOVER_L28D_BINGO_SLOTS'].astype(object).astype(float) 
df_all['M25_TURNOVER_L28D_BINGO_OTHER_CASINO'] = df_all['M25_TURNOVER_L28D_BINGO_OTHER_CASINO'].astype(object).astype(float) 
df_all['M25_TURNOVER_L28D_BINGO_VIRTUAL'] = df_all['M25_TURNOVER_L28D_BINGO_VIRTUAL'].astype(object).astype(float) 
df_all['M25_TURNOVER_L28D_BINGO_TABLE_GAMES'] = df_all['M25_TURNOVER_L28D_BINGO_TABLE_GAMES'].astype(object).astype(float) 
df_all['M25_TURNOVER_L28D_BINGO_OTHER'] = df_all['M25_TURNOVER_L28D_BINGO_OTHER'].astype(object).astype(float)

In [7]:
df_all['PLAYER_ID'] = df_all['PLAYER_ID'].astype(int).astype(str)
cols = df_all.select_dtypes(include=[np.number]).columns #Provide all columns as numbers
cols

Index(['ACTIVE_DAY_QTY', 'M20_SPENDFROMNORM', 'M02_TIMEONSITE',
       'MARKER_3_FREQ_PLAY_INCREASE', 'M04_DEPOSITDAYS', 'M05_FAILEDDEPOSITS',
       'M06_MULTIPLEPAYMENTMETHODS', 'M07_LATENIGHTPLAY', 'M19_TIMEONSITEL7D',
       'M01_DEPOSITAMOUNTINCREASE', 'M03_INCREASINGSTAKES',
       'MO8_TIMEBETWEENSESSIONS', 'MO9_DUPLICATEACCOUNTS', 'M10_SPEEDOFPLAY',
       'M11_INSESSIONTOPUP', 'M12_RGLIMITEXCEEDED', 'M13_CHAOTICPLAY',
       'M14_VARIETYOFGAMES', 'M15_YESTERDAYTIMEONSITE', 'M16_PLAYINWORKHOURS',
       'M17_BIGWINNODEPOSIT', 'M18_DEPOSIT_QTY', 'M21_INCREASINGSTAKESRATIO',
       'TENURE_DAYS', 'DAYS_SINCE_REGISTRATION', 'PLAYER_DAYS_L28D',
       'TURNOVER_L28D', 'NGR_L28D', 'DEPOSIT_L28D', 'WITHDRAWAL_L28D',
       'M03_INCREASINGSTAKES_BINGO', 'M03_INCREASINGSTAKE_SPORTS_INPLAY',
       'M03_INCREASINGSTAKES_PREMATCH', 'M03_INCREASINGSTAKE_SLOTS',
       'M03_INCREASINGSTAKES_OTHER_CASINO', 'M03_INCREASINGSTAKEs_VIRTUAL',
       'M03_INCREASINGSTAKES_TABLE_GAMES', 'M03_INCREASINGSTAKES_OTHER',
       'M02_TIMEONSITE_BINGO', 'M02_TIMEONSITE_SPORTS',
       'M02_TIMEONSITE_CASINO', 'M02_TIMEONSITE_POKER',
       'M07_LATENIGHTPLAY_BINGO', 'M07_LATENIGHTPLAY_SPORTS',
       'M07_LATENIGHTPLAY_CASINO', 'M07_LATENIGHTPLAY_POKER',
       'M13_CHAOTICPLAY_BINGO', 'M13_CHAOTICPLAY_SPORTS_INPLAY',
       'M13_CHAOTICPLAY_SPORTS_PREMATCH', 'M13_CHAOTICPLAY_SLOTS',
       'M13_CHAOTICPLAY_OTHER_CASINO', 'M13_CHAOTICPLAY_VIRTUAL',
       'M13_CHAOTICPLAY_TABLE_GAMES', 'M13_CHAOTICPLAY_OTHER',
       'M15_YESTERDAYTIMEONSITE_BINGO', 'M15_YESTERDAYTIMEONSITE_SPORTS',
       'M15_YESTERDAYTIMEONSITE_CASINO', 'M15_YESTERDAYTIMEONSITE_POKER',
       'M19_TIMEONSITEL7D_BINGO', 'M19_TIMEONSITEL7D_SPORTS',
       'M19_TIMEONSITEL7D_CASINO', 'M19_TIMEONSITEL7D_POKER',
       'M25_TURNOVER_L28D_BINGO', 'M25_TURNOVER_L28D_SPORTS_PREMATCH',
       'M25_TURNOVER_L28D_SPORTS_INPLAY', 'M25_TURNOVER_L28D_BINGO_SLOTS',
       'M25_TURNOVER_L28D_BINGO_OTHER_CASINO',
       'M25_TURNOVER_L28D_BINGO_VIRTUAL',
       'M25_TURNOVER_L28D_BINGO_TABLE_GAMES', 'M25_TURNOVER_L28D_BINGO_OTHER'],
      dtype='object')

In [8]:
import pickle
import joblib

model = joblib.load(open("PGv3_gbm_FINAL.pkl", "rb"))

In [12]:
proba_val = pd.DataFrame(model.predict_proba(df_all[cols]))
proba_val[0]

0         0.996830
1         0.967434
2         0.997534
3         0.991835
4         0.951424
            ...
192924    0.866245
192925    0.953625
192926    0.987435
192927    0.951457
192928    0.928795
Name: 0, Length: 192929, dtype: float64

In [13]:
df_all['PGv3_Probability'] = list(proba_val[1])

df_all.head()

,PLAYER_ID,Classification_Date,ACTIVE_DAY_QTY,M20_SPENDFROMNORM,M02_TIMEONSITE,MARKER_3_FREQ_PLAY_INCREASE,M04_DEPOSITDAYS,M05_FAILEDDEPOSITS,M06_MULTIPLEPAYMENTMETHODS,M07_LATENIGHTPLAY,...,M19_TIMEONSITEL7D_POKER,M25_TURNOVER_L28D_BINGO,M25_TURNOVER_L28D_SPORTS_PREMATCH,M25_TURNOVER_L28D_SPORTS_INPLAY,M25_TURNOVER_L28D_BINGO_SLOTS,M25_TURNOVER_L28D_BINGO_OTHER_CASINO,M25_TURNOVER_L28D_BINGO_VIRTUAL,M25_TURNOVER_L28D_BINGO_TABLE_GAMES,M25_TURNOVER_L28D_BINGO_OTHER,PGv3_Probability
0,21299973,2021-06-09,1649,0.00000,0.07792,0.07792,NaN,NaN,NaN,NaN,...,0.0,0.0,0.00,0.0,3.53025,0.00000,0.0,0.00000,0.00000,0.003170
1,184787803,2021-06-12,312,-5.18615,1.73618,1.73618,6.0,2.0,1.0,0.9,...,0.0,0.0,0.00,0.0,2948.13230,586.51747,0.0,87.58331,3493.75028,0.032566
2,190191163,2020-11-18,43,NaN,0.64863,0.64863,NaN,NaN,NaN,NaN,...,0.0,0.0,1.37,0.0,0.00000,0.00000,0.0,0.00000,19.84042,0.002466
3,190841223,2021-06-14,81,1.23077,2.22222,2.22222,2.0,NaN,1.0,NaN,...,0.0,0.0,0.00,0.0,40.78963,0.00000,0.0,0.00000,0.00000,0.008165
4,199207053,2020-12-30,32,NaN,9.37228,9.37228,2.0,NaN,1.0,NaN,...,0.0,0.0,0.00,0.0,1443.16313,28.41000,0.0,0.00000,0.00000,0.048576